#
# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: MPL-2.0
#

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "MPL-2.0"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
crypto-hash = "0.3.1"
easy_process = "0.1.3"
failure = "0.1.2"
failure_derive = "0.1.2"
hex = "0.3.2"
hyper = "0.11"
log = "0.4.5"
parse_duration = "1.0.1"
reqwest = "0.8.8"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_ini = "0.1.3"
serde_json = "1.0.27"
stderrlog = "0.4.1"
rand = "0.5.5"
walkdir = "2.2.5"
structopt = "0.2.10"

[build-dependencies]
git-version = "0.2.0"

[dev-dependencies]
tempfile = "3.0.4"
mockito = "0.13.0"
