# Copyright (C) 2017, 2018 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "updatehub"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
actix = "0.8"
actix-web = "1"
chrono = { version = "0.4", features = ["serde"] }
compress-tools = "0.1"
crypto-hash = "0.3"
derivative = "1"
easy_process = "0.1"
failure = "0.1"
futures = "0.1"
hex = "0.3"
infer = "0.1"
lazy_static = "1"
nix = "0.14"
parse_duration = "1"
pkg-schema = { path = "../updatehub-package-schema", package = "updatehub-package-schema" }
quale = "1"
rand = "0.7"
regex = "1"
reqwest = "=0.9.19"
serde = { version = "1", features = ["rc", "derive"] }
serde_ini = "0.2"
serde_json = "1"
slog = "2"
slog-async = "2"
slog-scope = "4"
slog-term = "2"
structopt = "0.2"
sys-mount = "1"
tempfile = "3"
timeout-readwrite = "0.2"
walkdir = "2"

[build-dependencies]
git-version = "0.3"

[dev-dependencies]
loopdev = "0.2"
mockito = "0.20"
pretty_assertions = "0.6"
tempfile = "3"
